name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: nix build
      run: nix build
    - name: nix flake check
      run: nix flake check
    - name: Verify nix run works
      run: nix run '.#' -- src/testdata/deployment.yaml
